/**
 * scripts/seed-vocab/generate-batch1-sql.ts
 *
 * Đọc data/vocab-enriched-batch1.json → validate Zod → sinh seed-batch1.sql.
 * Mọi row set `created_by = NULL` tường minh (từ hệ thống, mọi user thấy).
 * ON CONFLICT (word) WHERE created_by IS NULL DO NOTHING → chạy lại idempotent.
 *
 * Usage: yarn seed:batch1:gen
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { z } from 'zod'

const __dirname = dirname(fileURLToPath(import.meta.url))
const INPUT = resolve(__dirname, 'data/vocab-enriched-batch1.json')
const OUTPUT = resolve(__dirname, 'seed-batch1.sql')
const ROWS_PER_STATEMENT = 500

// Zod schema: khớp shape file JSON. Chấp nhận domain nullable + pos nullable.
const entrySchema = z.object({
  word: z.string().trim().min(1),
  meaning_vi: z.string().trim().min(1),
  example: z.string().trim().min(1),
  ipa: z.string().trim().min(1),
  band: z.enum(['A1', 'A2', 'B1', 'B2', 'C1', 'C2']),
  domain: z.string().trim().min(1).nullable(),
  pos: z.string().trim().min(1).nullable(),
  state: z.literal('New'),
  enriched_by: z.string().optional(),
})

type Entry = z.infer<typeof entrySchema>

// SQLite string literal: escape ' → ''
function sqlStr(s: string): string {
  return `'${s.replace(/'/g, "''")}'`
}
function sqlNullable(s: string | null | undefined): string {
  return s == null ? 'NULL' : sqlStr(s)
}

function main() {
  const raw = JSON.parse(readFileSync(INPUT, 'utf8')) as unknown[]
  if (!Array.isArray(raw)) {
    throw new Error(`Expected array, got ${typeof raw}`)
  }

  const entries: Entry[] = []
  const errors: { idx: number; word: unknown; issues: unknown }[] = []
  for (let i = 0; i < raw.length; i++) {
    const parsed = entrySchema.safeParse(raw[i])
    if (!parsed.success) {
      const rawObj = raw[i] as { word?: unknown }
      errors.push({ idx: i, word: rawObj?.word, issues: parsed.error.issues })
      continue
    }
    entries.push(parsed.data)
  }

  if (errors.length > 0) {
    console.error(`❌ ${errors.length} entries failed validation:`)
    console.error(JSON.stringify(errors.slice(0, 5), null, 2))
    if (errors.length > 5) console.error(`... và ${errors.length - 5} lỗi khác`)
    process.exit(1)
  }

  // Check duplicate word trong chính batch1 (unique constraint sẽ fail nếu có).
  const wordCounts = new Map<string, number>()
  for (const e of entries) wordCounts.set(e.word, (wordCounts.get(e.word) ?? 0) + 1)
  const dupes = [...wordCounts.entries()].filter(([, c]) => c > 1)
  if (dupes.length > 0) {
    console.error(`❌ Duplicate word trong batch1: ${dupes.map(([w, c]) => `${w}(${c})`).join(', ')}`)
    process.exit(1)
  }

  const now = Date.now()
  const cols = '(`word`, `meaning`, `example`, `ipa`, `topic`, `band`, `pos`, `created_by`, `created_at`, `updated_at`)'
  const conflict = 'ON CONFLICT (word) WHERE created_by IS NULL DO NOTHING'

  const chunks: string[] = []
  chunks.push('-- seed-batch1.sql — auto-generated by scripts/seed-vocab/generate-batch1-sql.ts')
  chunks.push('-- Input: data/vocab-enriched-batch1.json')
  chunks.push(`-- Rows: ${entries.length}`)
  chunks.push('-- Idempotent: ON CONFLICT (word) WHERE created_by IS NULL DO NOTHING')
  chunks.push('-- Apply: yarn wrangler d1 execute self-craft-db --local --file=scripts/seed-vocab/seed-batch1.sql')
  chunks.push('')

  for (let i = 0; i < entries.length; i += ROWS_PER_STATEMENT) {
    const slice = entries.slice(i, i + ROWS_PER_STATEMENT)
    const values = slice
      .map((e) => {
        return `(${sqlStr(e.word)}, ${sqlStr(e.meaning_vi)}, ${sqlStr(e.example)}, ${sqlStr(e.ipa)}, ${sqlNullable(e.domain)}, ${sqlStr(e.band)}, ${sqlNullable(e.pos)}, NULL, ${now}, ${now})`
      })
      .join(',\n  ')
    chunks.push(`INSERT INTO \`eng_vocab\` ${cols} VALUES\n  ${values}\n${conflict};`)
    chunks.push('')
  }

  const output = chunks.join('\n')
  writeFileSync(OUTPUT, output, 'utf8')

  // Stats: đếm theo band để đối chiếu với file nguồn (task acceptance #2).
  const byBand = new Map<string, number>()
  for (const e of entries) byBand.set(e.band, (byBand.get(e.band) ?? 0) + 1)
  const bandStats = [...byBand.entries()].sort(([a], [b]) => a.localeCompare(b))

  console.log(`✅ Đã sinh ${OUTPUT}`)
  console.log(`   ${entries.length} rows`)
  console.log(`   Phân bổ band: ${bandStats.map(([b, c]) => `${b}=${c}`).join(', ')}`)
}

main()
